.PHONY: clean All

All:
	@echo "----------Building project:[ UseMadeTemplate - Debug ]----------"
	@cd "UseMadeTemplate" && "$(MAKE)" -f  "UseMadeTemplate.mk"
clean:
	@echo "----------Cleaning project:[ UseMadeTemplate - Debug ]----------"
	@cd "UseMadeTemplate" && "$(MAKE)" -f  "UseMadeTemplate.mk" clean
